version: '3.5'

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - proxy-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - frontend
      - backend

  frontend:
    image: example-frontend:2.10
    container_name: example-frontend
    networks:
      - proxy-network

  backend:
    image: example-backend:2.10
    container_name: example-backend
    networks:
      - proxy-network
    environment:
     - REDIS_HOST=redis
     - POSTGRES_HOST=db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=example
     - POSTGRES_DATABASE=backend_db
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=example
     - POSTGRES_DB=backend_db
    container_name: example_backend_db
    volumes:
     - database:/var/lib/postgresql/data
    networks:
     - proxy-network

  redis:
    image: redis
    container_name: redis
    networks:
      - proxy-network


volumes:
  database:

networks:
  proxy-network:
