version: '3.5'

services:
  frontend:
    image: ml-kurkkumopo-frontend
    ports:
      - 8080:3000
    container_name: kurkkumopo-frontend
  
  backend:
    image: ml-kurkkumopo-backend
    container_name: kurkkumopo-backend
    volumes:
      - model:/src/model
    ports:
      - 5000:5000
  
  training:
    image: ml-kurkkumopo-training
    container_name: kurkkumopo-training
    volumes:
      - model:/src/model
      - ./imgs:/src/imgs

volumes:
  model:
