version: '3.5'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=example
     - POSTGRES_DB=backend_db
     - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: example_backend_db
    volumes:
     - ./postgres_database:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    volumes:
     - ./redis_database:/data

  frontend:
    image: devopsdockeruh/example-frontend
    ports:
     - 5000:5000

  backend:
    image: devopsdockeruh/example-backend
    ports: 
     - 8080:8080
    environment:
     - REDIS_HOST=redis
     - POSTGRES_HOST=db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=example
     - POSTGRES_DATABASE=backend_db
    depends_on:
      - db
      - redis
